version: '3.8'

services:
  passwordpattern:
    container_name: passwordpattern
    build: .
    volumes:
      - ./:/app
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d

